export const path = {
  HOMEPAGE: "/",
  PROFILE: "/user/profile",
  STATISTICS: "/user/stats",
  DASHBOARD: "/dashboard/overview",
  DASHBOARD_TOPICS: "/dashboard/topics",
  DASHBOARD_CREATE_TOPIC: "/dashboard/topic/create",
  DASHBOARD_STORIES: "/dashboard/stories",
  DASHBOARD_PENDING_STORIES: "/dashboard/stories/pending",
  DASHBOARD_USERS: "/dashboard/users",
  DASHBOARD_REPORTS: "/dashboard/reports",
  ANONYMOUS_PROFILE: "/user/profile/:userId",
  SETTING: "/user/setting",
  NEWSTORY: "/new-story",
  EDIT_STORY: "/edit-story/:storyId",
  STORY_DETAIL: "/:storyId",
  EDIT_PROFILE: "/user/profile/edit",
  EXPORE_TOPICS: "/explore-topics",
  EXPORE_STORIES: "/explore-stories/:topicId",
  SEARCH: "/search",
  TAG: "/tag/:slug",
} as const;
